### ISSUE TITLE
React native hockeyapp setup not complete

### ISSUE THREAD

**Issue by mangogogos** [slowpath/react-native-hockeyapp#10]
RNHockeyApp isn't showing up in my iOS NativeModules

Under my Libraries: RNHockeyApp.h/m
in my Podfile: pod 'HockeySDK'
in my AppDelegate.m:

```
#import "RNHockeyApp.h"
...
- (BOOL)application:(UIApplication *)application
          openURL:(NSURL *)url
          sourceApplication:(NSString *)sourceApplication
          annotation:(id)annotation
  {
    if( [[BITHockeyManager sharedHockeyManager].authenticator handleOpenURL:url
                                                        sourceApplication:sourceApplication
                                                               annotation:annotation])
    {
      return YES;
    }

    /* Your own custom URL handlers */

    return NO;
  }
```

and in Link Binary With Libraries on Build Phases: HockeySDK.framework

Everything compiles successfully but as I said RNHockeyApp is not appearing in NativeModules. Anything look wrong with my setup or any suggestions?

**Comment by iamladi** [comment]
@JBerendes updated Readme with correct instructions. Have a look and let me know if it solves the issue for you.

**Comment by mangogogos** [comment]
Sorry for not getting back to this sooner! I'm not sure what the issue I was having was but after updating all the files involved this seems to have been resolved. Cheers!

**Comment by ghost** [comment]
Add the following to your header search paths and make sure to set the recursive flag:
$(SRCROOT)/../node_modules/react-native-hockeyapp/RNHockeyApp
