### ISSUE TITLE
iOS doesn't work with rnpm link while Android does.  Would be nice to include in a way both worked

### ISSUE THREAD

**Issue by thadcodes** [slowpath/react-native-hockeyapp#16]
I think the issue is that the native module isn't setup as an xcode project to include.  I'm not an iOS developer so I don't really know how to properly fix it otherwise I would fix it myself.

**Comment by Partysun** [comment]
👍 +1

**Comment by Partysun** [comment]
Now I'm testing rnpm link, and it doesnt correct for android too. I fix MainActivity for build project like in instruction. I think rnpm feature is must have for libs like this.
