### ISSUE TITLE
Not seeing any update popup or dialogs for Android

### ISSUE THREAD

**Issue by jsphkhan** [slowpath/react-native-hockeyapp#22]
I have followed each and every step mentioned by you.
Configured the App Id inside my index.android.js file

componentWillMount() {
    HockeyApp.configure("ff27b86c87b547669e19faf4xxxxxxxxx", false);
  }

  componentDidMount() {
    console.log('test');
    HockeyApp.start();
    HockeyApp.checkForUpdate();
  }

Also made all the necessary changes inside the android folders.
I created 2 apps (version 1 & 1.1) and hosted them on HockeyApp with Mandatory update radio checked on for each of the versions.
I do not see any update dialogs when I install and launch the app. There are no errors as well. What am I missing. Kindly suggest.

Thanks.

**Comment by berickson1** [comment]
#23 should fix this. I was also seeing this in my app & tracked it down to a bug in the HockeyApp SDK itself

**Comment by jsphkhan** [comment]
Thanks I have updated the version to 4 after looking at your PR. Do I need to download the module again or just rebuild the project?

**Comment by jsphkhan** [comment]
Its working now. I rebuilt the project, uploaded the new apk in HockeyApp with Mandatory update radio checked on. When I launched the existing app on the device it did show me a update dialog :)

Thanks for your help.
Regards.
Joseph
