### ISSUE TITLE
Feature Request: User Authentication

### ISSUE THREAD

**Issue by berickson1** [slowpath/react-native-hockeyapp#3]
HockeyApp SDK supports the following:
Anonymous auth
Device UUID Auth
HockyApp User Login Auth
Email Auth
Web Auth

react-native-hockeyapp only supports anonymous.  Are there any plans to support additional authentication mechanisms?

**Comment by berickson1** [comment]
If there's no short term goals to making this happen, I'm willing to contribute and can look at iOS early next week

**Comment by iamladi** [comment]
@berickson1 I don't have the plan. So I would be really happy if you do it and I could probably do Android version. So feel free to work on it.

**Comment by berickson1** [comment]
Cool.  We should agree upon an interface.  Here's my proposal:
Function: HockeyApp.configure

Parameters:
HOCKEY_APP_ID:string
autoSendCrashReports:boolean (default = true)
authType enum (default = 0)
app_secret: string (default = "")

Enum values:
0 - No Auth
1- Email (& Secred) Auth
2 - HockeyApp User Login Auth (email & password)
3 - Device UUID Auth
4 - Web auth (iOS only)

If you're ok with this, I'll start on iOS. Thoughts?

**Comment by iamladi** [comment]
Looks good. :+1: 

Just one observation... Maybe the naming of the var could be all camel case?

**Comment by berickson1** [comment]
Sounds good, I wasn't sure what naming convention you preferred.

I've implemented iOS auth types. I'll hold off making a pull request because it will break android (differing api call signatures).
Take a look at it here: adfa03c7f4a80d6702ba1d32632fe5e7180f3ef3

Thoughts?

**Comment by berickson1** [comment]
Sounds good, I wasn't sure what naming convention you preferred.

I've implemented iOS auth types. I'll hold off making a pull request because it will break android (differing api call signatures).
Take a look at it here: 81e3793b6c2077f74d1e2003b89558558d67e632

Thoughts?

**Comment by iamladi** [comment]
Looks good to me with 1 comment on the commit. Feel free to create PR and next week when I'm back from skiing I'll write the Android version of it.

**Comment by berickson1** [comment]
@martincik, @rspeyer implemented the Android piece.  Feel free to take a look here: da086f6709cae77f5dc514333d21758a0ee18cb6

I'll put up a pull request tomorrow for iOS/Android combined

**Comment by lostintangent** [comment]
Awesome! I was actually planning to send a PR for this, but you beat me to the punch :)

**Comment by iamladi** [comment]
@berickson1 @rspeyer Looks good! Let's do PR.

**Comment by iamladi** [comment]
@rspeyer Can you create PR for Android impl. of the Auth?

**Comment by rspeyer** [comment]
@martincik it looks like it has already been pulled in via the `auth` branch - here is the relevant diff: https://github.com/slowpath/react-native-hockeyapp/compare/81e3793b6c2077f74d1e2003b89558558d67e632...master

**Comment by iamladi** [comment]
@rspeyer Great. Didn't notice. ;) Thank you.
