### ISSUE TITLE
RN 28 incompatible types

### ISSUE THREAD

**Issue by jeveloper** [slowpath/react-native-hockeyapp#34]
cannot be converted to Application

error: incompatible types: MainActivity cannot be converted to Application
            new RNHockeyAppPackage(this),
                                   ^

This should lib should work for RN 28

0.5

**Comment by jeveloper** [comment]
Only version 0.4.2 will work with RN28

@slowpath can you let me contribute to this project?

A bunch of things need updates

thanks

**Comment by iamladi** [comment]
@jeveloper Yes of course. Contribution is always welcomed. You can create PR and I'll review it and merge it for you. Thank you!

**Comment by jeveloper** [comment]
Great @martincik  ! 

By the way, my parents live in Syrovice , so i've been all over CZ :) Love your country
