### ISSUE TITLE
Update popup not showing on checkForUpdate (iOS)

### ISSUE THREAD

**Issue by johanarnor** [slowpath/react-native-hockeyapp#40]
Hi!

I'm having some troubles displaying the update popup when running the checkForUpdate method. The code is straight from the guide and sessions as well as crash reports are registered in the HockeyApp dashboard. No errors are shown in the logs.

```
  componentWillMount () {
    HockeyApp.configure('APP_ID', true)
    console.log('WILL MOUNT', HockeyApp)
  }

  componentDidMount () {
    HockeyApp.start()
    HockeyApp.checkForUpdate()
  }
```

Steps:
- Upload version 1.0.0 to HockeyApp
- Install it on the iPhone
- Upload version 1.0.1 to HockeyApp
- Restart the app on the iPhone and wait for the popup (which never shows)

All help is much appreciated!

**Comment by johanarnor** [comment]
It started working, so I'm closing the issue.

**Comment by Jaafar-abusair** [comment]
@johanarnor  how it works for you?

**Comment by Anima-t3d** [comment]
I am having the same issue, anyone experienced this and got a solution? The android version does show the update dialogue.

Also anyone got the number of installs showing HockeyApp? Do we need to do something specific for it to work?

**Comment by Anima-t3d** [comment]
@johanarnor @Jaafar-abusair Any solutions? Initially I thought it had to do with the permission to show alert window. But using the react-native `Alert.alert` works fine on iOS.

**Comment by Anima-t3d** [comment]
I finally got it to work. Before using `react-native-hockeyapp` I used the official HockeyApp installation instructions for iOS. 

**Solution**:
1. I had to revert the steps I had taken for integrating the official SDK.
1. I made the changes to AppDelegate.m (although this seems optional to me?)

If you wish to use Device UUID authentication or Web authentication, the following must be added to ios/AppDelegate.m
```
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
  if( [[BITHockeyManager sharedHockeyManager].authenticator handleOpenURL:url
                                                        sourceApplication:sourceApplication
                                                               annotation:annotation]) {
    return YES;
  }

  /* Your own custom URL handlers */

  return NO;
}
```
