### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by krivachy** [slowpath/react-native-hockeyapp#43]
We're encountering the same bug that is fixed in this commit: https://github.com/slowpath/react-native-hockeyapp/commit/224a4472cae41777a23c928821ace169f3a34e97

Can you please publish a new version of react-native-hockeyapp?

**Comment by bourgois** [comment]
@martincik Could you indeed do a new release? All my fixes still require to pull from react-native-hockeyapp.git#25f65e1b61dd151360ad31e27e9fa6ba0ab15eae commit rather than from a 'official' version... THANKS!

**Comment by iamladi** [comment]
I'll put it on my TODO for today/tomorrow.

**Comment by iamladi** [comment]
A new version 0.5.1 is out. Please test it. Feedback welcomed.
