### ISSUE TITLE
Android implementation documentation is out of date

### ISSUE THREAD

**Issue by jasonmerino** [slowpath/react-native-hockeyapp#5]
The `MainActivity.java` file in newer versions of React Native is structured drastically different than it used to be. The documentation in the README.md file is out of date.

**Comment by iamladi** [comment]
Good point. Thank you for reporting. Whenever I will find a energy to update it I will make new instructions.

NOTE: As of React Native 0.18 the MainActivity.java is different in the react-native init.

**Comment by iamladi** [comment]
@jasonmerino Update in the master.

**Comment by jasonmerino** [comment]
Awesome! Thanks @martincik :smile:
