### ISSUE TITLE
Possibly wrong path in README.md

### ISSUE THREAD

**Issue by 0x46616c6b** [slowpath/react-native-hockeyapp#50]
Is there possibly a wrong include in the README.md? The module will installed under `../node_modules/hockeyapp-react-native` and not `../node_modules/react-native-hockeyapp`

Or do I something wrong?

Actual in the `README.md`

```
include ':react-native-hockeyapp', ':app'
project(':react-native-hockeyapp').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-hockeyapp/android')
```

Expected to build in `android/settings.gradle`
```
include ':react-native-hockeyapp'
project(':react-native-hockeyapp').projectDir = new File(rootProject.projectDir, '../node_modules/hockeyapp-react-native/android')
```

**Comment by bourgois** [comment]
Hi. It does install under ../node_modules/react-native-hockeyapp for us...
