### ISSUE TITLE
CheckForUpdate not showing update view though availble

### ISSUE THREAD

**Issue by dilipmukkapati** [slowpath/react-native-hockeyapp#70]
Hi,

I integrated this library and testing on android to checkForUpdate I don't see updates though app is on older version than hockeyapp. I see the **feedbacks are collected and updated** on hockeyapp server but checkForUpdate not working. Have you ever faced this issue before? Following is the code.

```
     import * as HockeyApp from 'react-native-hockeyapp';

    export class AboutPage extends Component {
    constructor(props) {
        super(props)
    }

   // this function is called upon click of button
    checkUpdate() {
        try{
            console.log('testing1...');
            let appId = '*****************************',
                autoSendCrashes = true;

            HockeyApp.configure(appId, autoSendCrashes);

            HockeyApp.start();
            HockeyApp.checkForUpdate();
            // HockeyApp.feedback();
            console.log('testing2...');
        } catch(e) {
            console.log(e);
        }
    }
    ....
```

**Comment by ethras** [comment]
same issue here

**Comment by dilipmukkapati** [comment]
Did little more debugging in this part, I see UpdateManager.register(currentActivity, _token) is called successfully. I placed a toast message in the checkForUpdate (of react-native-hockeyapp) which is called successfully and _token is having the value passed.

Updatemanager is not showing up, not sure about it. gonna place a support ticket to hockeyapp and see how it goes. I'll post it here, if you have any good news please lemme know.

**Comment by dilipmukkapati** [comment]
The library is good, the configuration in the hockeyapp.net says **beta** as release type in my case. After changing it to **Enterprise** everything worked.
