### ISSUE TITLE
wanted: guidance resolving overridden build settings that come with react-native OOTB

### ISSUE THREAD

**Issue by tomprogers** [slowpath/react-native-hockeyapp#9]
CocoaPods installation throws a couple of warnings:

```
[!] The `myapp [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-myapp/Pods-myapp.debug.xcconfig'. This can lead to problems with the CocoaPods installation
   - Use the `$(inherited)` flag, or
   - Remove the build settings from the target.

[!] The `myapp [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-myapp/Pods-myapp.release.xcconfig'. This can lead to problems with the CocoaPods installation
   - Use the `$(inherited)` flag, or
   - Remove the build settings from the target.
```

This is when run against a pretty small react-native project (rn version 0.20.0) with just a couple of third-party react-native modules, which makes me think this will be a common problem that developers will face. If that's accurate, providing some guidance in the README for resolving it would help welcome.

**Comment by mangogogos** [comment]
+1

**Comment by iamladi** [comment]
I this something that is related to this NPM package? It feels to me like it's either CocoaPods issue or RN upgrade.
